"""add_knowledge_models

Revision ID: 33054934b880
Revises: 94efd2ab5432
Create Date: 2026-06-21 14:34:28.234679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33054934b880'
down_revision: Union[str, None] = '94efd2ab5432'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_documents',
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('filepath', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('document_id')
    )
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_documents_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_documents_filepath'), ['filepath'], unique=True)

    op.create_table('knowledge_ingestion_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('total_documents', sa.Integer(), nullable=False),
    sa.Column('total_chunks', sa.Integer(), nullable=False),
    sa.Column('indexed_documents', sa.Integer(), nullable=False),
    sa.Column('skipped_documents', sa.Integer(), nullable=False),
    sa.Column('reindexed_documents', sa.Integer(), nullable=False),
    sa.Column('deleted_documents', sa.Integer(), nullable=False),
    sa.Column('last_ingested_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_chunks',
    sa.Column('chunk_id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('heading_hierarchy', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.document_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    with op.batch_alter_table('knowledge_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_chunks_chunk_id'), ['chunk_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_chunks_chunk_id'))

    op.drop_table('knowledge_chunks')
    op.drop_table('knowledge_ingestion_metrics')
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_filepath'))
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_document_id'))

    op.drop_table('knowledge_documents')
    # ### end Alembic commands ###
