"""add_episodic_memory_tables

Revision ID: 3fee697e8d21
Revises: 6fae9924a500
Create Date: 2026-06-22 17:03:09.459864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fee697e8d21'
down_revision: Union[str, None] = '6fae9924a500'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_episodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('memory_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=False),
    sa.Column('recall_count', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('key_decisions', sa.JSON(), nullable=False),
    sa.Column('important_facts', sa.JSON(), nullable=False),
    sa.Column('open_tasks', sa.JSON(), nullable=False),
    sa.Column('importance_score', sa.Float(), nullable=False),
    sa.Column('embedding_vector', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project_memories.project_memory_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_runtime_sessions.runtime_session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memory_episodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memory_episodes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_episodes_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_episodes_session_id'), ['session_id'], unique=False)

    op.create_table('memory_recalls',
    sa.Column('recall_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('episode_id', sa.String(), nullable=False),
    sa.Column('recalled_at', sa.DateTime(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('retrieval_reason', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['memory_episodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_runtime_sessions.runtime_session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recall_id')
    )
    with op.batch_alter_table('memory_recalls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memory_recalls_episode_id'), ['episode_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_recalls_recall_id'), ['recall_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_recalls_session_id'), ['session_id'], unique=False)

    op.create_table('open_tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('episode_id', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['episode_id'], ['memory_episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('open_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_open_tasks_episode_id'), ['episode_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_open_tasks_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('open_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_open_tasks_id'))
        batch_op.drop_index(batch_op.f('ix_open_tasks_episode_id'))

    op.drop_table('open_tasks')
    with op.batch_alter_table('memory_recalls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memory_recalls_session_id'))
        batch_op.drop_index(batch_op.f('ix_memory_recalls_recall_id'))
        batch_op.drop_index(batch_op.f('ix_memory_recalls_episode_id'))

    op.drop_table('memory_recalls')
    with op.batch_alter_table('memory_episodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memory_episodes_session_id'))
        batch_op.drop_index(batch_op.f('ix_memory_episodes_project_id'))
        batch_op.drop_index(batch_op.f('ix_memory_episodes_id'))

    op.drop_table('memory_episodes')
    # ### end Alembic commands ###
