"""add_conversation_title_and_message_version

Revision ID: 5062ef77e76a
Revises: a1b2c3d4e5f6
Create Date: 2026-06-23 17:14:14.288479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5062ef77e76a'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_runtime_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conversation_title', sa.String(length=80), nullable=True))
        batch_op.drop_index(batch_op.f('ix_crs_correlation_id'))
        batch_op.create_index(batch_op.f('ix_conversation_runtime_sessions_correlation_id'), ['correlation_id'], unique=False)

    with op.batch_alter_table('conversation_turns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_version', sa.Integer(), nullable=False))

    with op.batch_alter_table('metrics_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metrics_snapshots_snapshot_id'), ['snapshot_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metrics_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metrics_snapshots_snapshot_id'))

    with op.batch_alter_table('conversation_turns', schema=None) as batch_op:
        batch_op.drop_column('message_version')

    with op.batch_alter_table('conversation_runtime_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_runtime_sessions_correlation_id'))
        batch_op.create_index(batch_op.f('ix_crs_correlation_id'), ['correlation_id'], unique=False)
        batch_op.drop_column('conversation_title')

    # ### end Alembic commands ###
