"""ms10_tool_framework

Revision ID: 59de429697f9
Revises: bd9cd0a66b49
Create Date: 2026-06-21 16:09:44.718756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59de429697f9'
down_revision: Union[str, None] = 'bd9cd0a66b49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool_executions',
    sa.Column('execution_id', sa.String(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=True),
    sa.Column('tool_name', sa.String(), nullable=False),
    sa.Column('tool_version', sa.String(), nullable=False),
    sa.Column('capability_level', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('output_summary', sa.Text(), nullable=True),
    sa.Column('output_truncated', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trace_id'], ['cognitive_traces.trace_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('execution_id')
    )
    with op.batch_alter_table('tool_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tool_executions_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_executions_trace_id'), ['trace_id'], unique=False)

    op.create_table('approval_requests',
    sa.Column('approval_id', sa.String(), nullable=False),
    sa.Column('execution_id', sa.String(), nullable=False),
    sa.Column('tool_name', sa.String(), nullable=False),
    sa.Column('capability_level', sa.String(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['tool_executions.execution_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('approval_id'),
    sa.UniqueConstraint('execution_id')
    )
    with op.batch_alter_table('approval_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_requests_approval_id'), ['approval_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approval_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_requests_approval_id'))

    op.drop_table('approval_requests')
    with op.batch_alter_table('tool_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tool_executions_trace_id'))
        batch_op.drop_index(batch_op.f('ix_tool_executions_execution_id'))

    op.drop_table('tool_executions')
    # ### end Alembic commands ###
