"""create_revised_persistence_schema

Revision ID: 5b0b01e71e2b
Revises: None
Create Date: 2026-06-21 12:23:49.505265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b0b01e71e2b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal_tracker',
    sa.Column('goal_id', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('target_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('goal_id')
    )
    with op.batch_alter_table('goal_tracker', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goal_tracker_goal_id'), ['goal_id'], unique=False)

    op.create_table('learning_history',
    sa.Column('concept_id', sa.String(), nullable=False),
    sa.Column('concept_name', sa.String(), nullable=False),
    sa.Column('mastery_score', sa.Integer(), nullable=False),
    sa.Column('last_reviewed', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('concept_id')
    )
    with op.batch_alter_table('learning_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_history_concept_id'), ['concept_id'], unique=False)

    op.create_table('project_tracker',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=False),
    sa.Column('tech_stack', sa.JSON(), nullable=True),
    sa.Column('historical_adr_keys', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('project_id')
    )
    with op.batch_alter_table('project_tracker', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_tracker_project_id'), ['project_id'], unique=False)

    op.create_table('sessions',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_session_id'), ['session_id'], unique=False)

    op.create_table('memory_events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('primary_modality', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    with op.batch_alter_table('memory_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memory_events_event_id'), ['event_id'], unique=False)

    op.create_table('event_payloads_audio',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('audio_file_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['memory_events.event_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('event_payloads_text',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('system_prompt_injected', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['memory_events.event_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('event_payloads_workspace',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('active_file', sa.String(), nullable=True),
    sa.Column('cursor_line', sa.Integer(), nullable=True),
    sa.Column('selected_code', sa.Text(), nullable=True),
    sa.Column('terminal_stderr', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['memory_events.event_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_payloads_workspace')
    op.drop_table('event_payloads_text')
    op.drop_table('event_payloads_audio')
    with op.batch_alter_table('memory_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memory_events_event_id'))

    op.drop_table('memory_events')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_session_id'))

    op.drop_table('sessions')
    with op.batch_alter_table('project_tracker', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_tracker_project_id'))

    op.drop_table('project_tracker')
    with op.batch_alter_table('learning_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_history_concept_id'))

    op.drop_table('learning_history')
    with op.batch_alter_table('goal_tracker', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goal_tracker_goal_id'))

    op.drop_table('goal_tracker')
    # ### end Alembic commands ###
