"""add_realtime_runtime_tables

Revision ID: 6cd15c54d880
Revises: 7c180eb31d18
Create Date: 2026-06-22 11:13:56.774629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cd15c54d880'
down_revision: Union[str, None] = '7c180eb31d18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_runtime_sessions',
    sa.Column('runtime_session_id', sa.String(), nullable=False),
    sa.Column('voice_session_id', sa.String(), nullable=True),
    sa.Column('conversation_state', sa.String(), nullable=False),
    sa.Column('current_turn_owner', sa.String(), nullable=False),
    sa.Column('interruption_count', sa.Integer(), nullable=False),
    sa.Column('total_listening_ms', sa.Integer(), nullable=False),
    sa.Column('total_thinking_ms', sa.Integer(), nullable=False),
    sa.Column('total_speaking_ms', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['voice_session_id'], ['voice_sessions.voice_session_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('runtime_session_id')
    )
    with op.batch_alter_table('conversation_runtime_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_runtime_sessions_runtime_session_id'), ['runtime_session_id'], unique=False)

    op.create_table('conversation_runtime_traces',
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('runtime_session_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('event_sequence', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('event_metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['runtime_session_id'], ['conversation_runtime_sessions.runtime_session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trace_id')
    )
    with op.batch_alter_table('conversation_runtime_traces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_runtime_traces_trace_id'), ['trace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_runtime_traces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_runtime_traces_trace_id'))

    op.drop_table('conversation_runtime_traces')
    with op.batch_alter_table('conversation_runtime_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_runtime_sessions_runtime_session_id'))

    op.drop_table('conversation_runtime_sessions')
    # ### end Alembic commands ###
