"""add_milestone17_models

Revision ID: 6fae9924a500
Revises: 8a947d70ffd3
Create Date: 2026-06-22 15:56:55.170130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fae9924a500'
down_revision: Union[str, None] = '8a947d70ffd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_metrics',
    sa.Column('metrics_id', sa.String(), nullable=False),
    sa.Column('runtime_session_id', sa.String(), nullable=False),
    sa.Column('total_turns', sa.Integer(), nullable=False),
    sa.Column('average_turn_latency_ms', sa.Float(), nullable=False),
    sa.Column('average_stt_latency_ms', sa.Float(), nullable=False),
    sa.Column('average_llm_latency_ms', sa.Float(), nullable=False),
    sa.Column('average_tts_latency_ms', sa.Float(), nullable=False),
    sa.Column('total_interruptions', sa.Integer(), nullable=False),
    sa.Column('playback_dropped_chunks', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['runtime_session_id'], ['conversation_runtime_sessions.runtime_session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('metrics_id')
    )
    with op.batch_alter_table('conversation_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_metrics_metrics_id'), ['metrics_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_metrics_runtime_session_id'), ['runtime_session_id'], unique=True)

    op.create_table('conversation_turns',
    sa.Column('turn_id', sa.String(), nullable=False),
    sa.Column('runtime_session_id', sa.String(), nullable=False),
    sa.Column('voice_session_id', sa.String(), nullable=True),
    sa.Column('user_text', sa.Text(), nullable=False),
    sa.Column('assistant_text', sa.Text(), nullable=False),
    sa.Column('prompt_hash', sa.String(), nullable=True),
    sa.Column('provider_name', sa.String(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('cognitive_trace_id', sa.String(), nullable=True),
    sa.Column('ai_response_id', sa.String(), nullable=True),
    sa.Column('segment_count', sa.Integer(), nullable=False),
    sa.Column('response_truncated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ai_response_id'], ['ai_responses.response_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cognitive_trace_id'], ['cognitive_traces.trace_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['runtime_session_id'], ['conversation_runtime_sessions.runtime_session_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voice_session_id'], ['voice_sessions.voice_session_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('turn_id')
    )
    with op.batch_alter_table('conversation_turns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_turns_ai_response_id'), ['ai_response_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_turns_cognitive_trace_id'), ['cognitive_trace_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_turns_runtime_session_id'), ['runtime_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_turns_turn_id'), ['turn_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_turns_voice_session_id'), ['voice_session_id'], unique=False)

    with op.batch_alter_table('conversation_runtime_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conversation_session_state', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('session_summary_status', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_runtime_sessions', schema=None) as batch_op:
        batch_op.drop_column('session_summary_status')
        batch_op.drop_column('conversation_session_state')

    with op.batch_alter_table('conversation_turns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_turns_voice_session_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_turns_turn_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_turns_runtime_session_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_turns_cognitive_trace_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_turns_ai_response_id'))

    op.drop_table('conversation_turns')
    with op.batch_alter_table('conversation_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_metrics_runtime_session_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_metrics_metrics_id'))

    op.drop_table('conversation_metrics')
    # ### end Alembic commands ###
