"""add_voice_transport_infrastructure

Revision ID: 7c180eb31d18
Revises: f8e2261a3af0
Create Date: 2026-06-22 10:31:25.444946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c180eb31d18'
down_revision: Union[str, None] = 'f8e2261a3af0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice_sessions',
    sa.Column('voice_session_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('websocket_client_id', sa.String(), nullable=False),
    sa.Column('transport_instance_id', sa.String(), nullable=True),
    sa.Column('reconnect_count', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('frames_received', sa.Integer(), nullable=False),
    sa.Column('frames_sent', sa.Integer(), nullable=False),
    sa.Column('bytes_received', sa.Integer(), nullable=False),
    sa.Column('bytes_sent', sa.Integer(), nullable=False),
    sa.Column('dropped_frames', sa.Integer(), nullable=False),
    sa.Column('missing_frames', sa.Integer(), nullable=False),
    sa.Column('out_of_order_frames', sa.Integer(), nullable=False),
    sa.Column('average_latency_ms', sa.Float(), nullable=False),
    sa.Column('disconnect_reason', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('voice_session_id')
    )
    with op.batch_alter_table('voice_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voice_sessions_voice_session_id'), ['voice_session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voice_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voice_sessions_voice_session_id'))

    op.drop_table('voice_sessions')
    # ### end Alembic commands ###
