"""add_provider_health_records

Revision ID: 824b9c0a2923
Revises: 6cd15c54d880
Create Date: 2026-06-22 12:07:40.592009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '824b9c0a2923'
down_revision: Union[str, None] = '6cd15c54d880'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_health_records',
    sa.Column('record_id', sa.String(), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.Column('provider_type', sa.String(), nullable=False),
    sa.Column('healthy', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('timeout_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('runtime_session_id', sa.String(), nullable=True),
    sa.Column('voice_session_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('record_id')
    )
    with op.batch_alter_table('provider_health_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_health_records_record_id'), ['record_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provider_health_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_health_records_record_id'))

    op.drop_table('provider_health_records')
    # ### end Alembic commands ###
