"""add provider sessions and conversation messages tables

Revision ID: 8a947d70ffd3
Revises: 824b9c0a2923
Create Date: 2026-06-22 15:15:21.972394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a947d70ffd3'
down_revision: Union[str, None] = '824b9c0a2923'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_sessions',
    sa.Column('provider_session_id', sa.String(), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.Column('runtime_session_id', sa.String(), nullable=True),
    sa.Column('voice_session_id', sa.String(), nullable=True),
    sa.Column('provider_state', sa.String(), nullable=False),
    sa.Column('connected_at', sa.DateTime(), nullable=False),
    sa.Column('disconnected_at', sa.DateTime(), nullable=True),
    sa.Column('disconnect_reason', sa.String(), nullable=True),
    sa.Column('messages_sent', sa.Integer(), nullable=False),
    sa.Column('messages_received', sa.Integer(), nullable=False),
    sa.Column('audio_frames_sent', sa.Integer(), nullable=False),
    sa.Column('audio_frames_received', sa.Integer(), nullable=False),
    sa.Column('interruptions', sa.Integer(), nullable=False),
    sa.Column('total_tokens_in', sa.Integer(), nullable=True),
    sa.Column('total_tokens_out', sa.Integer(), nullable=True),
    sa.Column('average_response_latency_ms', sa.Float(), nullable=True),
    sa.Column('max_response_latency_ms', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['runtime_session_id'], ['conversation_runtime_sessions.runtime_session_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['voice_session_id'], ['voice_sessions.voice_session_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('provider_session_id')
    )
    with op.batch_alter_table('provider_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_sessions_provider_session_id'), ['provider_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_sessions_runtime_session_id'), ['runtime_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_sessions_voice_session_id'), ['voice_session_id'], unique=False)

    op.create_table('provider_conversation_messages',
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('provider_session_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['provider_session_id'], ['provider_sessions.provider_session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    with op.batch_alter_table('provider_conversation_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_conversation_messages_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_conversation_messages_provider_session_id'), ['provider_session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provider_conversation_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_conversation_messages_provider_session_id'))
        batch_op.drop_index(batch_op.f('ix_provider_conversation_messages_message_id'))

    op.drop_table('provider_conversation_messages')
    with op.batch_alter_table('provider_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_sessions_voice_session_id'))
        batch_op.drop_index(batch_op.f('ix_provider_sessions_runtime_session_id'))
        batch_op.drop_index(batch_op.f('ix_provider_sessions_provider_session_id'))

    op.drop_table('provider_sessions')
    # ### end Alembic commands ###
