"""add_workspace_intelligence

Revision ID: bd9cd0a66b49
Revises: e7c808e226ca
Create Date: 2026-06-21 15:51:50.763109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd9cd0a66b49'
down_revision: Union[str, None] = 'e7c808e226ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_snapshots',
    sa.Column('snapshot_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('repo_name', sa.String(), nullable=False),
    sa.Column('repo_path', sa.String(), nullable=False),
    sa.Column('active_file_path', sa.String(), nullable=True),
    sa.Column('active_file_language', sa.String(), nullable=True),
    sa.Column('cursor_line', sa.Integer(), nullable=True),
    sa.Column('cursor_column', sa.Integer(), nullable=True),
    sa.Column('selection_content', sa.Text(), nullable=True),
    sa.Column('selection_truncated', sa.Boolean(), nullable=False),
    sa.Column('git_branch', sa.String(), nullable=True),
    sa.Column('git_status', sa.JSON(), nullable=False),
    sa.Column('git_recent_commits', sa.JSON(), nullable=False),
    sa.Column('detected_languages', sa.JSON(), nullable=False),
    sa.Column('detected_frameworks', sa.JSON(), nullable=False),
    sa.Column('scan_limit_reached', sa.Boolean(), nullable=False),
    sa.Column('workspace_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    with op.batch_alter_table('workspace_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspace_snapshots_snapshot_id'), ['snapshot_id'], unique=False)

    op.create_table('workspace_events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('snapshot_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['workspace_snapshots.snapshot_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('event_id')
    )
    with op.batch_alter_table('workspace_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspace_events_event_id'), ['event_id'], unique=False)

    with op.batch_alter_table('cognitive_traces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workspace_snapshot_id', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_cognitive_traces_workspace_snapshot_id', 'workspace_snapshots', ['workspace_snapshot_id'], ['snapshot_id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cognitive_traces', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cognitive_traces_workspace_snapshot_id', type_='foreignkey')
        batch_op.drop_column('workspace_snapshot_id')

    with op.batch_alter_table('workspace_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspace_events_event_id'))

    op.drop_table('workspace_events')
    with op.batch_alter_table('workspace_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspace_snapshots_snapshot_id'))

    op.drop_table('workspace_snapshots')
    # ### end Alembic commands ###
