"""add_llm_gateway_persistence

Revision ID: e7c808e226ca
Revises: f624f99aac0e
Create Date: 2026-06-21 15:39:38.626657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7c808e226ca'
down_revision: Union[str, None] = 'f624f99aac0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_responses',
    sa.Column('response_id', sa.String(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trace_id'], ['cognitive_traces.trace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('response_id'),
    sa.UniqueConstraint('trace_id')
    )
    with op.batch_alter_table('ai_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_responses_response_id'), ['response_id'], unique=False)

    op.create_table('conversation_messages',
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trace_id'], ['cognitive_traces.trace_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('message_id')
    )
    with op.batch_alter_table('conversation_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_messages_message_id'), ['message_id'], unique=False)

    with op.batch_alter_table('cognitive_traces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prompt_hash', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cognitive_traces', schema=None) as batch_op:
        batch_op.drop_column('prompt_hash')

    with op.batch_alter_table('conversation_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_messages_message_id'))

    op.drop_table('conversation_messages')
    with op.batch_alter_table('ai_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_responses_response_id'))

    op.drop_table('ai_responses')
    # ### end Alembic commands ###
