"""add_cognitive_trace

Revision ID: f624f99aac0e
Revises: 33054934b880
Create Date: 2026-06-21 14:54:00.154623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f624f99aac0e'
down_revision: Union[str, None] = '33054934b880'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cognitive_traces',
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('selected_skills', sa.JSON(), nullable=False),
    sa.Column('knowledge_chunks', sa.JSON(), nullable=False),
    sa.Column('memory_items', sa.JSON(), nullable=False),
    sa.Column('prompt_version', sa.String(), nullable=False),
    sa.Column('final_prompt_preview', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('trace_id')
    )
    with op.batch_alter_table('cognitive_traces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cognitive_traces_trace_id'), ['trace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cognitive_traces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cognitive_traces_trace_id'))

    op.drop_table('cognitive_traces')
    # ### end Alembic commands ###
