"""ms11_controlled_execution

Revision ID: f6c10719232a
Revises: 59de429697f9
Create Date: 2026-06-22 07:14:38.380569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6c10719232a'
down_revision: Union[str, None] = '59de429697f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool_executions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exit_code', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('stdout', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('stderr', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('stdout_truncated', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('stderr_truncated', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('timed_out', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('requested_by', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool_executions', schema=None) as batch_op:
        batch_op.drop_column('requested_by')
        batch_op.drop_column('timed_out')
        batch_op.drop_column('stderr_truncated')
        batch_op.drop_column('stdout_truncated')
        batch_op.drop_column('stderr')
        batch_op.drop_column('stdout')
        batch_op.drop_column('exit_code')

    # ### end Alembic commands ###
