"""ms12_conversation_intelligence

Revision ID: f8e2261a3af0
Revises: f6c10719232a
Create Date: 2026-06-22 07:41:13.690341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8e2261a3af0'
down_revision: Union[str, None] = 'f6c10719232a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_memories',
    sa.Column('project_memory_id', sa.String(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_milestone', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('active_goals', sa.JSON(), nullable=False),
    sa.Column('open_questions', sa.JSON(), nullable=False),
    sa.Column('next_steps', sa.JSON(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('project_memory_id')
    )
    with op.batch_alter_table('project_memories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_memories_project_memory_id'), ['project_memory_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_memories_project_name'), ['project_name'], unique=True)

    op.create_table('project_snapshots',
    sa.Column('snapshot_id', sa.String(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=False),
    sa.Column('milestone', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('decisions', sa.JSON(), nullable=False),
    sa.Column('open_questions', sa.JSON(), nullable=False),
    sa.Column('next_steps', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    with op.batch_alter_table('project_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_snapshots_project_name'), ['project_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_snapshots_snapshot_id'), ['snapshot_id'], unique=False)

    op.create_table('conversation_profiles',
    sa.Column('profile_id', sa.String(), nullable=False),
    sa.Column('interaction_count', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('active_project_id', sa.String(), nullable=True),
    sa.Column('current_focus', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['active_project_id'], ['project_memories.project_memory_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('profile_id')
    )
    with op.batch_alter_table('conversation_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_profiles_profile_id'), ['profile_id'], unique=False)

    op.create_table('preference_memories',
    sa.Column('preference_id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('source_session_id', sa.String(), nullable=True),
    sa.Column('source_trace_id', sa.String(), nullable=True),
    sa.Column('last_confirmed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_session_id'], ['sessions.session_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_trace_id'], ['cognitive_traces.trace_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('preference_id')
    )
    with op.batch_alter_table('preference_memories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_preference_memories_preference_id'), ['preference_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preference_memories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_preference_memories_preference_id'))

    op.drop_table('preference_memories')
    with op.batch_alter_table('conversation_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_profiles_profile_id'))

    op.drop_table('conversation_profiles')
    with op.batch_alter_table('project_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_snapshots_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_project_snapshots_project_name'))

    op.drop_table('project_snapshots')
    with op.batch_alter_table('project_memories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_memories_project_name'))
        batch_op.drop_index(batch_op.f('ix_project_memories_project_memory_id'))

    op.drop_table('project_memories')
    # ### end Alembic commands ###
